### ISSUE TITLE
Fully support for HTTP in WearHttpHelper

### ISSUE THREAD

**Issue by xanscale** [googlesamples/android-WearCompanionLibrary#10]
actually WearHttpHelper has a very poor http support.
- can't use custom request header
- can't use custom request body format (like JSON)
- can't use method out of GET/POST
- can't read response header
- and maybe more

two question:
1) this library is deprecated or is fully supported by google?
2) there is any update scheduled ?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
