### ISSUE TITLE
Typo in javadoc of method getDataItemsSynchronous in WearManager

### ISSUE THREAD

**Issue by AladinQ** [googlesamples/android-WearCompanionLibrary#2]
I guess there is a typo in the [javadoc of method _getDataItemsSynchronous(long timeoutInMillis)_ in _WearManager_ class](https://github.com/googlesamples/android-WearCompanionLibrary/blob/master/WCL/src/main/java/com/google/devrel/wcl/WearManager.java#L411) on the word **asynchronously** (should be <b>synchronously</b>) . Additionally, it lacks the indication of `This should only be called on a non-UI thread.` like other synchronous methods.

Instead of 

> ```
> /**
>  * Retrieves data items asynchronously from the Android Wear network. A {@code timeoutInMillis}
>  * is required to specify the maximum length of time, in milliseconds, that the thread should be
>  * blocked. Caller needs to call {@code release()} on the returned {@link DataItemBuffer} when
>  * done.
>  */
> ```

It should be

> ```
> /**
>  * Retrieves data items <b>synchronously</b> from the Android Wear network. This should only be called on a non-UI thread.
>  * A {@code timeoutInMillis} is required to specify the maximum length of time, in milliseconds, that the thread should be blocked.
>  * Caller needs to call {@code release()} on the returned {@link DataItemBuffer} when done.
>  */
> ```

**Comment by naddaf** [comment]
Yes, that is a typo, will fix in the next update; thanks for bringing that to my attention.

**Comment by AladinQ** [comment]
You're welcome, thanks for your library.
There is another one in the PDF documentation (not sure it's worth it to open another issue for it) in the snippet code of **Examples and Snippets** _1. Sending a message to nodes that provide certain capability_:
`wearManager.sendMessage(targetNode, SOME_PATH, bytes);` 
should be
`wearManager.sendMessage(targetNode.getId(), SOME_PATH, bytes);` .

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
