### ISSUE TITLE
"Size of the transferred file doesn't match the original size" when using WearFileTransfer facility

### ISSUE THREAD

**Issue by BoD** [googlesamples/android-WearCompanionLibrary#5]
I am trying to use the `WearFileTransfer` facility to upload a file from the handheld to the watch.  Every time I do it I see this log on the watch:
`Size of the transferred file doesn't match the original size`
Then, I receive the `onWearableFileReceivedResult` callback, with a `SUCCESS` status, but if I look at the file, it has a 0 byte length (the original file on the handheld is not empty).

Any idea?

I can provide a sample project showing the issue if necessary.

**Comment by BoD** [comment]
As a side note, while trying to investigate this issue, and if I'm not mistaken, it seems to me that the `Channel` that is created when transferring the file, is never closed.  I am not sure if this is on purpose or a potential issue.

**Comment by naddaf** [comment]
I believe the demo sample has an example of this, can you try that?

**Comment by BoD** [comment]
Oh I missed it.  I'll have a look and get back to you.

**Comment by BoD** [comment]
Ok I can reproduce the issue on the sample app if I tweak it a bit. 

If I change the file name to be unique (different every time the method is called), then I have the `Size of the transferred file doesn't match the original size` log on the handheld app.

To do this I simply changed this line:
`.setTargetName(TEXT_FILE_NAME)`
to this:
`.setTargetName(TEXT_FILE_NAME + System.currentTimeMillis())`

My guess: 
- the callback is called too soon (while the transfer is still in progress)
- if you test several times, the file is already there (from the previous test) with the correct size, so the lib has the impression that it worked
- if the file name is different every time, this doesn't happen

I think the proper way to know if the transfer is finished is to follow this advice from the Javadoc of `Channel.receiveFile`: 

> To be notified when the file is ready, install a ChannelApi.ChannelListener, with an implementation of onInputClosed(Channel, int, int).

If I'm not mistaken (I may have missed it), this is not done in the library.

**Comment by naddaf** [comment]
Thanks for the report and PR.
